version: "3"

services:
    postgres:
        image: postgres:15.2-alpine
        ports:
            - "5433:5432"
        environment:
            POSTGRES_USER: "${DB_USERNAME}"
            POSTGRES_PASSWORD: "${DB_PASSWORD}"
            POSTGRES_DB: "${DB_DATABASE}"
